spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.108.55:3306/sell?useSSL=false&characterEncoding=utf-8&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  context-path: /sell